export const COLLECTIONS = {
  COMPANIES: "companies",
  USERS: "users",
  COMPANY_USERS: "companyUsers",
  COMPANY_SETTINGS: "companySettings",
  INVITATIONS: "invitations",
  USER_ROLES: "userRoles",

  CHART_OF_ACCOUNTS: "chartOfAccounts",
  JOURNAL_ENTRIES: "journalEntries",
  JOURNAL_LINES: "journalLines",

  INVOICES: "invoices",
  INVOICE_ITEMS: "invoiceItems",
  BILLS: "bills",
  EXPENSES: "expenses",
  SALES_ORDERS: "salesOrders",
  PURCHASE_ORDERS: "purchaseOrders",

  EMPLOYEES: "employees",
  CONTRACTORS: "contractors",
  ADVANCES: "advances",
  TIME_ENTRIES: "timeEntries",
  EMPLOYEE_ALLOWANCES: "employeeAllowances",
  EMPLOYEE_PAYROLL_PROFILES: "employeePayrollProfiles",
  PAYROLL_RUNS: "payrollRuns",
  PAYROLL_ITEMS: "payrollItems",
  PAYROLL_ADDITIONS: "payrollAdditions",
  PAYROLL_JOURNALS: "payrollJournals",
  PAYE_TAX_BANDS: "payeTaxBands",
  PAYROLL_STATUTORY_RATES: "payrollStatutoryRates",

  CUSTOMERS: "customers",
  VENDORS: "vendors",
  PROJECTS: "projects",
  PROJECT_ACTIVITY_LOGS: "projectActivityLogs",
  PROJECT_EXPENSES: "projectExpenses",
  APPROVAL_REQUESTS: "approvalRequests",
  PRODUCTS: "products",
  FIXED_ASSETS: "fixedAssets",
  ASSET_CATEGORIES: "assetCategories",
  DEPRECIATION_ENTRIES: "depreciationEntries",
  INVENTORY_ITEMS: "inventoryItems",
  STOCK_MOVEMENTS: "stockMovements",
  PRICE_LISTS: "priceLists",
  PRICE_LIST_ITEMS: "priceListItems",

  BANK_ACCOUNTS: "bankAccounts",
  BANK_TRANSACTIONS: "bankTransactions",
  FINANCIAL_YEARS: "financialYears",
  FINANCIAL_PERIODS: "financialPeriods",
  CASH_RECONCILIATIONS: "cashReconciliations",
  RECONCILIATIONS: "reconciliations",
  PERIOD_LOCKS: "periodLocks",

  NOTIFICATIONS: "notifications",
  AUDIT_LOGS: "auditLogs",
} as const;

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];
